/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mjzuelvnowutvarghfbm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qenVlbHZub3d1dHZhcmdoZmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NTEzOTgsImV4cCI6MjA4NTAyNzM5OH0.V7a6fvu_itMGxV8oWaw5DfXngD--CuPnnU2QKsMVjGM"